//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carmotub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Intervention = new HashSet<Intervention>();
            this.PhotoClient = new HashSet<PhotoClient>();
        }
    
        public int identifiant { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string adresse { get; set; }
        public string code_postal { get; set; }
        public string ville { get; set; }
        public string etage { get; set; }
        public string escalier { get; set; }
        public string telephone_1 { get; set; }
        public string commentaire { get; set; }
        public string telephone_2 { get; set; }
        public string code { get; set; }
        public string rdv { get; set; }
        public string recommande_par { get; set; }
        public string voie { get; set; }
        public string numero_adresse { get; set; }
    
        public virtual ICollection<Intervention> Intervention { get; set; }
        public virtual ICollection<PhotoClient> PhotoClient { get; set; }
    }
}
