//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carmotub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intervention
    {
        public int identifiant { get; set; }
        public Nullable<int> identifiant_client { get; set; }
        public string date_intervention { get; set; }
        public string type_chaudiere { get; set; }
        public string carnet { get; set; }
        public string nature { get; set; }
        public string montant { get; set; }
        public string montant_old { get; set; }
        public string numero_cheque { get; set; }
        public string type_paiement { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
