//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carmotub
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoClient
    {
        public int identifiant { get; set; }
        public string uri { get; set; }
        public Nullable<int> identifiant_client { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
